# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: ConsoleApp / Create artifacts
on:
    workflow_dispatch:
    push:
        tags: 
            - 'v*.*.*'
            - 'v*.*.*-*'

permissions:
    packages: read

jobs:
    create-artifacts:
        name: Create artifacts
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os: [ ubuntu-latest, windows-latest, macos-14 ]
        env:
            DOTNET_NOLOGO: true
        
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            
            - name: Setup .NET SDK
              uses: actions/setup-dotnet@v4
              with:
                global-json-file: global.json

            - name: Install .NET tools
              run: dotnet tool restore

            - name: Update project files with GitVersion
              run: dotnet tool run dotnet-gitversion /updateprojectfiles

            - name: Compile project (Windows)
              if: ${{ runner.os == 'Windows' }}
              run: |
                dotnet publish ./src/ConsoleApp/ --configuration "Release" --runtime "win-x64" --output "./build/ConsoleApp/"

            - name: Compile project (Linux)
              if: ${{ runner.os == 'Linux' }}
              run: |
                dotnet publish ./src/ConsoleApp/ --configuration "Release" --runtime "linux-x64" --output "./build/ConsoleApp/"

            - name: Compile project (macOS)
              if: ${{ runner.os == 'macOS' }}
              run: |
                dotnet publish ./src/ConsoleApp/ --configuration "Release" --runtime "osx-arm64" --output "./build/ConsoleApp-arm64/";
                dotnet publish ./src/ConsoleApp/ --configuration "Release" --runtime "osx-x64" --output "./build/ConsoleApp-x64/";

            - name: List files
              shell: pwsh
              run: |
                Get-ChildItem -Path "${{ github.workspace }}/build/" -Recurse | ForEach-Object { "$($PSItem.FullName)" }

            - name: Create artifact (Windows)
              uses: actions/upload-artifact@v4
              if: ${{ runner.os == 'Windows' }}
              with:
                name: "gh-releasegen_win-x64_${{ github.ref_type == 'tag' && github.ref_name || github.sha }}"
                path: ${{ github.workspace }}/build/ConsoleApp/**/*
                if-no-files-found: error

            - name: Create artifact (Linux)
              uses: actions/upload-artifact@v4
              if: ${{ runner.os == 'Linux' }}
              with:
                name: "gh-releasegen_linux-x64_${{ github.ref_type == 'tag' && github.ref_name || github.sha }}"
                path: ${{ github.workspace }}/build/ConsoleApp/**/*
                if-no-files-found: error

            - name: Create artifact (macOS arm64)
              uses: actions/upload-artifact@v4
              if: ${{ runner.os == 'macOS' }}
              with:
                name: "gh-releasegen_osx-arm64_${{ github.ref_type == 'tag' && github.ref_name || github.sha }}"
                path: ${{ github.workspace }}/build/ConsoleApp-arm64/**/*
                if-no-files-found: error

            - name: Create artifact (macOS x64)
              uses: actions/upload-artifact@v4
              if: ${{ runner.os == 'macOS' }}
              with:
                name: "gh-releasegen_osx-x64_${{ github.ref_type == 'tag' && github.ref_name || github.sha }}"
                path: ${{ github.workspace }}/build/ConsoleApp-x64/**/*
                if-no-files-found: error